### ISSUE TITLE
What is the prediction folder?

### ISSUE THREAD

**Issue by kainataltaf** [vevenom/ScanNet-Layout#1]
What is the prediction folder? Currently, I am passing an arbitrary name to the argument.

`python evaluate_3d_layouts.py --pred "./predict/" --eval_2D --eval_3D`

It gives me this error : 

```
File "evaluate_3d_layouts.py", line 132, in <module>
    pred_labelme_data = json.load(open(pred_llabel_json_path))
FileNotFoundError: [Errno 2] No such file or directory: './predict/labels_json/scene0707_00/367.json'
```

**Comment by vevenom** [comment]
Prediction folder is the folder where you put predictions/output of your method.

Just to state the obvious, this script is used to evaluate the quality of your predictions.
